steps:
  # 1. Gradle 빌드 (Maven을 사용한다면 `gradle` 대신 `mvn`을 사용)
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']

  # 2. App Engine에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# 빌드 후 자동으로 생성된 이미지를 GCP에서 관리
images:
  - 'gcr.io/$PROJECT_ID/TravelGoServer'