#spring:
#  profiles:
#    include: aws, s3
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#  thymeleaf:
#    prefix: classpath:/templates/


spring:
  profiles:
    include: aws, s3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# swagger
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /
    enabled: true
    groups-order: DESC
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


automatic_scaling:
  min_instances: 1  # 최소 1개의 인스턴스를 항상 유지
  max_instances: 10 # 최대 인스턴스 수는 필요에 따라 조정